server:
  port: 9090

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    hikari:
      auto-commit: false
    url: jdbc:postgresql://localhost:5432/BeekeepersShop_db
    username: postgres
    password: Kostylygin2004
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  web:
    resources:
      add-mappings: false

logging:
  level:
    org:
      springframework:
        web:
          debug

app:
  client:
    url: http://localhost:4200
